[pytest]
markers =
    smoke: быстрые проверки основных сценариев
    regression: регрессионные тесты
    slow: медленные тесты
    api: тесты через API
    ui: тесты фронта
    bd: тесты с бд
    ii: просто проба теста